[tool.poetry]
name = "tuneinsight"
version = "0.4.0"
description = "Diapason is the official Python SDK for the Tune Insight Agent API"
authors = ["Tune Insight SA"]
license = "Apache-2.0"
include = ["src/tuneinsight/api/**/*.py"]
readme = "src/tuneinsight/README.md"

[tool.poetry.dependencies]
python = ">= 3.7.1, < 3.11"
python-keycloak = "^0.27.0"
pandas = "^1.3.5"
PyYAML = "^6.0"
#cloudpickle = "^2.0.0" // TODO: to add in the future to run python on backend
wheel = "^0.37.1"
pylint = "^2.13.2"
docker = "^6.0.1"
notebook = "^6.4.11"
python-dotenv = "^0.21.0"
pyvcf3 = "^1.0.3"
python-dateutil = "^2.8.0"
matplotlib = "^3.5.0"

# Required by ge_co_rest_api
httpx = ">=0.15.4,<0.24.0"
attrs = ">=21.3.0"
selenium = "^4.9.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
