/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "cryptoso.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// GetLastError returns the last error generated by the Go code
//
extern char* GetLastError();

// NewPolynomialCKKSParams creates a new set of cryptosystem CKKS given test params for polynomial evaluation
// and returns them serialized with Marshall Binary and encoded in base64
//
extern char* NewPolynomialCKKSParams();

// NewTestPredictionCKKSParams creates a new set of cryptosystem CKKS given test params for prediction
// and returns them serialized with Marshall Binary and encoded in base64
//
extern char* NewTestPredictionCKKSParams();

// LoadB64CryptoSystem Set Parameters to load cryptosystem
//
extern char* LoadB64CryptoSystem(char* b64params);

// GenKeyPair generates a serialized key pair using as first argument the id of the cryptosystem
//
extern char* GenKeyPair(char* id);

// EncryptFloatMatrix encrypts a float matrix to a Ciphertable
//
extern void* EncryptFloatMatrix(char* id, char* plaintext);

// DecryptCipherTable decrypts a ciphertable
//
extern char* DecryptCipherTable(char* id, void* ciphertext, size_t textSize);

// GenRelinearizationKey generates a relinearization using as first argument the id of the cryptosystem
// write a test that calls one of those functions
// pass failing payload: catch error in python
//
extern char* GenRelinearizationKey(char* id);

// EncodeBase64Url encodes binary data into Base64 URL
//
extern char* EncodeBase64Url(void* bytes, size_t size);

// DecodeBase64Url decodes binary data from Base64 URL
//
extern void* DecodeBase64Url(char* base64data);

// DecodeBase64UrlSize decodes binary data from Base64 URL
//
extern size_t DecodeBase64UrlSize(char* base64data);

// Create an evaluator for subsequent mathematical operations
//
extern char* GenerateEvaluator(char* id);

// Create an encoder for subsequent mathematical operations
//
extern char* GenerateEncoder(char* id);

// Create an encoder for subsequent mathematical operations
//
extern char* GenerateEncryptor(char* id);

// Create a decryptor for subsequent mathematical operations
//
extern char* GenerateDecryptor(char* id);

// Instantiate the scheme for subsequent mathematical operations
//
extern char* InstantiateScheme(char* id);

// Encrypt a numeric value
//
extern void* EncryptNumber(char* id, char* number);

// DecryptNumber decrypts a ciphertable
//
extern void* DecryptNumber(char* id, void* ciphertext, size_t textSize);

// Add adds two encrypted numbers
//
extern void* Add(char* id, void* number1, void* number2, size_t number1Size, size_t number2Size);

// Multiply multiplies two encrypted numbers
//
extern void* Multiply(char* id, void* number1, void* number2, size_t number1Size, size_t number2Size);

// PolynomialEvaluation evaluates an encrypted number on a polynomial
//
extern void* PolynomialEvaluation(char* id, void* number, size_t numberSize);

// GenPolynomial creates a Polynomial
//
extern char* GenPolynomial(char* id, char* polynomialCoefficients, size_t polynomialCoefficientsSize);

#ifdef __cplusplus
}
#endif
