from enum import Enum


class Capability(str, Enum):
    VIEWPROJECTS = "ViewProjects"
    VIEWPROJECTSTATUSES = "ViewProjectStatuses"
    CREATEPROJECTS = "CreateProjects"
    EDITPROJECTS = "EditProjects"
    REQUESTPROJECTAUTHORIZATION = "RequestProjectAuthorization"
    AUTHORIZEPROJECTS = "AuthorizeProjects"
    ACCESSANYPROJECT = "AccessAnyProject"
    DELETEPROJECTS = "DeleteProjects"
    DELETEANYPROJECT = "DeleteAnyProject"
    SETANYDATASOURCE = "SetAnyDataSource"
    RUNPROJECTS = "RunProjects"
    VIEWRESULTS = "ViewResults"
    VIEWANYRESULT = "ViewAnyResult"
    VIEWCOMPUTATIONS = "ViewComputations"
    VIEWANYCOMPUTATION = "ViewAnyComputation"
    DELETECOMPUTATIONS = "DeleteComputations"
    DELETEANYCOMPUTATION = "DeleteAnyComputation"
    RUNCOMPUTATIONS = "RunComputations"
    VIEWPARAMS = "ViewParams"
    MANAGEBOOKMARKS = "ManageBookmarks"
    REQUESTDISTRIBUTEDCOMPUTATIONS = "RequestDistributedComputations"
    SENDCOMPUTATIONMESSAGES = "SendComputationMessages"
    VIEWDATAOBJECTS = "ViewDataObjects"
    VIEWANYDATAOBJECT = "ViewAnyDataObject"
    CREATEDATAOBJECTS = "CreateDataObjects"
    EDITDATAOBJECTS = "EditDataObjects"
    EDITANYDATAOBJECT = "EditAnyDataObject"
    DELETEDATAOBJECTS = "DeleteDataObjects"
    DELETEANYDATAOBJECT = "DeleteAnyDataObject"
    VIEWDATASOURCETYPES = "ViewDataSourceTypes"
    GENERATEMOCKDATA = "GenerateMockData"
    VIEWDATASOURCES = "ViewDataSources"
    VIEWANYDATASOURCE = "ViewAnyDataSource"
    EDITDATASOURCES = "EditDataSources"
    EDITANYDATASOURCE = "EditAnyDataSource"
    CREATEDATASOURCES = "CreateDataSources"
    QUERYDATASOURCES = "QueryDataSources"
    QUERYANYDATASOURCE = "QueryAnyDataSource"
    DELETEDATASOURCES = "DeleteDataSources"
    DELETEANYDATASOURCE = "DeleteAnyDataSource"
    VIEWREMOTESELECTIONS = "ViewRemoteSelections"
    VIEWQUERIES = "ViewQueries"
    PROMPTLLMS = "PromptLLMs"
    SEARCHONTOLOGIES = "SearchOntologies"
    VIEWTASKPROGRESS = "ViewTaskProgress"
    VIEWSETTINGS = "ViewSettings"
    EDITSETTINGS = "EditSettings"
    MANAGESTORAGE = "ManageStorage"
    VIEWCONFIG = "ViewConfig"
    MANAGEUSERS = "ManageUsers"
    VIEWAUDITLOGS = "ViewAuditLogs"
    VIEWNETWORK = "ViewNetwork"
    SYNCNETWORKS = "SyncNetworks"
    GETREMOTEINFOS = "GetRemoteInfos"

    def __str__(self) -> str:
        return str(self.value)
