from typing import Any, Dict, List, Type, TypeVar, Union

import attr

from ..types import UNSET, Unset

T = TypeVar("T", bound="Term")


@attr.s(auto_attribs=True)
class Term:
    """represents a single term from any terminology/ontology stored by the instance.

    Attributes:
        omop_concept_id (Union[Unset, str]): the OMOP concept ID for this term.
        breadcrumb (Union[Unset, str]):
        children (Union[Unset, str]):
        code (Union[Unset, str]):
        data_source_id (Union[Unset, None, str]): id of the data source from which this ontology term was loaded.
        description (Union[Unset, str]):
        domain (Union[Unset, str]): the name of domain for this term (equivalent to the OMOP domain ID).
        id (Union[Unset, str]): Unique identifier for this terminology term locally generated by the instance.
        level (Union[Unset, float]):
        name (Union[Unset, str]):
        occurrence (Union[Unset, None, float]): represents the number of patients in the data source for which there
            exists at least one reference to this term.
        occurrence_network (Union[Unset, None, float]): represents the number of patients across all data sources in the
            network, for which there exists at least one reference to this term.
        ontology (Union[Unset, str]):
        parents (Union[Unset, str]):
        total_occurrence (Union[Unset, None, int]): represents the total number of patients across all data sources for
            which there exists at least one reference to this term.
        uri (Union[Unset, str]):
        version (Union[Unset, str]):
    """

    omop_concept_id: Union[Unset, str] = UNSET
    breadcrumb: Union[Unset, str] = UNSET
    children: Union[Unset, str] = UNSET
    code: Union[Unset, str] = UNSET
    data_source_id: Union[Unset, None, str] = UNSET
    description: Union[Unset, str] = UNSET
    domain: Union[Unset, str] = UNSET
    id: Union[Unset, str] = UNSET
    level: Union[Unset, float] = UNSET
    name: Union[Unset, str] = UNSET
    occurrence: Union[Unset, None, float] = UNSET
    occurrence_network: Union[Unset, None, float] = UNSET
    ontology: Union[Unset, str] = UNSET
    parents: Union[Unset, str] = UNSET
    total_occurrence: Union[Unset, None, int] = UNSET
    uri: Union[Unset, str] = UNSET
    version: Union[Unset, str] = UNSET
    additional_properties: Dict[str, Any] = attr.ib(init=False, factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        omop_concept_id = self.omop_concept_id
        breadcrumb = self.breadcrumb
        children = self.children
        code = self.code
        data_source_id = self.data_source_id
        description = self.description
        domain = self.domain
        id = self.id
        level = self.level
        name = self.name
        occurrence = self.occurrence
        occurrence_network = self.occurrence_network
        ontology = self.ontology
        parents = self.parents
        total_occurrence = self.total_occurrence
        uri = self.uri
        version = self.version

        field_dict: Dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if omop_concept_id is not UNSET:
            field_dict["OMOPConceptId"] = omop_concept_id
        if breadcrumb is not UNSET:
            field_dict["breadcrumb"] = breadcrumb
        if children is not UNSET:
            field_dict["children"] = children
        if code is not UNSET:
            field_dict["code"] = code
        if data_source_id is not UNSET:
            field_dict["dataSourceId"] = data_source_id
        if description is not UNSET:
            field_dict["description"] = description
        if domain is not UNSET:
            field_dict["domain"] = domain
        if id is not UNSET:
            field_dict["id"] = id
        if level is not UNSET:
            field_dict["level"] = level
        if name is not UNSET:
            field_dict["name"] = name
        if occurrence is not UNSET:
            field_dict["occurrence"] = occurrence
        if occurrence_network is not UNSET:
            field_dict["occurrenceNetwork"] = occurrence_network
        if ontology is not UNSET:
            field_dict["ontology"] = ontology
        if parents is not UNSET:
            field_dict["parents"] = parents
        if total_occurrence is not UNSET:
            field_dict["totalOccurrence"] = total_occurrence
        if uri is not UNSET:
            field_dict["uri"] = uri
        if version is not UNSET:
            field_dict["version"] = version

        return field_dict

    @classmethod
    def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
        d = src_dict.copy()
        omop_concept_id = d.pop("OMOPConceptId", UNSET)

        breadcrumb = d.pop("breadcrumb", UNSET)

        children = d.pop("children", UNSET)

        code = d.pop("code", UNSET)

        data_source_id = d.pop("dataSourceId", UNSET)

        description = d.pop("description", UNSET)

        domain = d.pop("domain", UNSET)

        id = d.pop("id", UNSET)

        level = d.pop("level", UNSET)

        name = d.pop("name", UNSET)

        occurrence = d.pop("occurrence", UNSET)

        occurrence_network = d.pop("occurrenceNetwork", UNSET)

        ontology = d.pop("ontology", UNSET)

        parents = d.pop("parents", UNSET)

        total_occurrence = d.pop("totalOccurrence", UNSET)

        uri = d.pop("uri", UNSET)

        version = d.pop("version", UNSET)

        term = cls(
            omop_concept_id=omop_concept_id,
            breadcrumb=breadcrumb,
            children=children,
            code=code,
            data_source_id=data_source_id,
            description=description,
            domain=domain,
            id=id,
            level=level,
            name=name,
            occurrence=occurrence,
            occurrence_network=occurrence_network,
            ontology=ontology,
            parents=parents,
            total_occurrence=total_occurrence,
            uri=uri,
            version=version,
        )

        term.additional_properties = d
        return term

    @property
    def additional_keys(self) -> List[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
