from typing import TYPE_CHECKING, Any, Dict, List, Type, TypeVar, Union

import attr

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.term_description_translations import TermDescriptionTranslations
    from ..models.term_name_translations import TermNameTranslations
    from ..models.term_occurrence import TermOccurrence


T = TypeVar("T", bound="Term")


@attr.s(auto_attribs=True)
class Term:
    """represents a single term from any terminology/ontology stored by the instance.

    Attributes:
        omop_concept_id (Union[Unset, str]): the OMOP concept ID for this term.
        aggregated_occurrence (Union[Unset, TermOccurrence]): Represents a number of occurrences of a term in a data
            source.
            More specifically, given a specific term from an ontology, this object
            stores the number of patients that have at least one record referencing this term in the data source.
            Moreover, this object also stores other useful metadata and statistics about the term.
        breadcrumb (Union[Unset, str]):
        children (Union[Unset, str]):
        code (Union[Unset, str]):
        data_source_id (Union[Unset, None, str]): id of the data source from which this ontology term was loaded.
        description (Union[Unset, str]):
        description_translations (Union[Unset, TermDescriptionTranslations]): mapping from language code to correponding
            term description.
        domain (Union[Unset, str]): the name of domain for this term (equivalent to the OMOP domain ID).
        id (Union[Unset, str]): Unique identifier for this terminology term locally generated by the instance.
        level (Union[Unset, float]):
        name (Union[Unset, str]):
        name_translations (Union[Unset, TermNameTranslations]): mapping from language code to correponding term label.
        occurrences (Union[Unset, List['TermOccurrence']]): the list of all occurrence data for this term.
        ontology (Union[Unset, str]):
        parents (Union[Unset, str]):
        privacy_budget_allocated (Union[Unset, float]): privacy budget allocated to this term in its ontology tree.
        skipped_for_catalog (Union[Unset, bool]): if true, the count and distribution for this term is not computed
            during the catalog build.
        total_children (Union[Unset, float]):
        total_descendant_occurrence (Union[Unset, None, int]): represents the total number of patients across all data
            sources for which there exists at least one reference to any descendant of this term.
        total_occurrence (Union[Unset, None, int]): represents the total number of patients across all data sources on
            this instance for which there exists at least one reference to this term.
        uri (Union[Unset, str]):
        version (Union[Unset, str]):
    """

    omop_concept_id: Union[Unset, str] = UNSET
    aggregated_occurrence: Union[Unset, "TermOccurrence"] = UNSET
    breadcrumb: Union[Unset, str] = UNSET
    children: Union[Unset, str] = UNSET
    code: Union[Unset, str] = UNSET
    data_source_id: Union[Unset, None, str] = UNSET
    description: Union[Unset, str] = UNSET
    description_translations: Union[Unset, "TermDescriptionTranslations"] = UNSET
    domain: Union[Unset, str] = UNSET
    id: Union[Unset, str] = UNSET
    level: Union[Unset, float] = UNSET
    name: Union[Unset, str] = UNSET
    name_translations: Union[Unset, "TermNameTranslations"] = UNSET
    occurrences: Union[Unset, List["TermOccurrence"]] = UNSET
    ontology: Union[Unset, str] = UNSET
    parents: Union[Unset, str] = UNSET
    privacy_budget_allocated: Union[Unset, float] = UNSET
    skipped_for_catalog: Union[Unset, bool] = UNSET
    total_children: Union[Unset, float] = UNSET
    total_descendant_occurrence: Union[Unset, None, int] = UNSET
    total_occurrence: Union[Unset, None, int] = UNSET
    uri: Union[Unset, str] = UNSET
    version: Union[Unset, str] = UNSET
    additional_properties: Dict[str, Any] = attr.ib(init=False, factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        omop_concept_id = self.omop_concept_id
        aggregated_occurrence: Union[Unset, Dict[str, Any]] = UNSET
        if not isinstance(self.aggregated_occurrence, Unset):
            aggregated_occurrence = self.aggregated_occurrence.to_dict()

        breadcrumb = self.breadcrumb
        children = self.children
        code = self.code
        data_source_id = self.data_source_id
        description = self.description
        description_translations: Union[Unset, Dict[str, Any]] = UNSET
        if not isinstance(self.description_translations, Unset):
            description_translations = self.description_translations.to_dict()

        domain = self.domain
        id = self.id
        level = self.level
        name = self.name
        name_translations: Union[Unset, Dict[str, Any]] = UNSET
        if not isinstance(self.name_translations, Unset):
            name_translations = self.name_translations.to_dict()

        occurrences: Union[Unset, List[Dict[str, Any]]] = UNSET
        if not isinstance(self.occurrences, Unset):
            occurrences = []
            for occurrences_item_data in self.occurrences:
                occurrences_item = occurrences_item_data.to_dict()

                occurrences.append(occurrences_item)

        ontology = self.ontology
        parents = self.parents
        privacy_budget_allocated = self.privacy_budget_allocated
        skipped_for_catalog = self.skipped_for_catalog
        total_children = self.total_children
        total_descendant_occurrence = self.total_descendant_occurrence
        total_occurrence = self.total_occurrence
        uri = self.uri
        version = self.version

        field_dict: Dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if omop_concept_id is not UNSET:
            field_dict["OMOPConceptId"] = omop_concept_id
        if aggregated_occurrence is not UNSET:
            field_dict["aggregatedOccurrence"] = aggregated_occurrence
        if breadcrumb is not UNSET:
            field_dict["breadcrumb"] = breadcrumb
        if children is not UNSET:
            field_dict["children"] = children
        if code is not UNSET:
            field_dict["code"] = code
        if data_source_id is not UNSET:
            field_dict["dataSourceId"] = data_source_id
        if description is not UNSET:
            field_dict["description"] = description
        if description_translations is not UNSET:
            field_dict["descriptionTranslations"] = description_translations
        if domain is not UNSET:
            field_dict["domain"] = domain
        if id is not UNSET:
            field_dict["id"] = id
        if level is not UNSET:
            field_dict["level"] = level
        if name is not UNSET:
            field_dict["name"] = name
        if name_translations is not UNSET:
            field_dict["nameTranslations"] = name_translations
        if occurrences is not UNSET:
            field_dict["occurrences"] = occurrences
        if ontology is not UNSET:
            field_dict["ontology"] = ontology
        if parents is not UNSET:
            field_dict["parents"] = parents
        if privacy_budget_allocated is not UNSET:
            field_dict["privacyBudgetAllocated"] = privacy_budget_allocated
        if skipped_for_catalog is not UNSET:
            field_dict["skippedForCatalog"] = skipped_for_catalog
        if total_children is not UNSET:
            field_dict["totalChildren"] = total_children
        if total_descendant_occurrence is not UNSET:
            field_dict["totalDescendantOccurrence"] = total_descendant_occurrence
        if total_occurrence is not UNSET:
            field_dict["totalOccurrence"] = total_occurrence
        if uri is not UNSET:
            field_dict["uri"] = uri
        if version is not UNSET:
            field_dict["version"] = version

        return field_dict

    @classmethod
    def from_dict(cls: Type[T], src_dict: Dict[str, Any]) -> T:
        from ..models.term_description_translations import TermDescriptionTranslations
        from ..models.term_name_translations import TermNameTranslations
        from ..models.term_occurrence import TermOccurrence

        d = src_dict.copy()
        omop_concept_id = d.pop("OMOPConceptId", UNSET)

        _aggregated_occurrence = d.pop("aggregatedOccurrence", UNSET)
        aggregated_occurrence: Union[Unset, TermOccurrence]
        if isinstance(_aggregated_occurrence, Unset):
            aggregated_occurrence = UNSET
        else:
            aggregated_occurrence = TermOccurrence.from_dict(_aggregated_occurrence)

        breadcrumb = d.pop("breadcrumb", UNSET)

        children = d.pop("children", UNSET)

        code = d.pop("code", UNSET)

        data_source_id = d.pop("dataSourceId", UNSET)

        description = d.pop("description", UNSET)

        _description_translations = d.pop("descriptionTranslations", UNSET)
        description_translations: Union[Unset, TermDescriptionTranslations]
        if isinstance(_description_translations, Unset):
            description_translations = UNSET
        else:
            description_translations = TermDescriptionTranslations.from_dict(_description_translations)

        domain = d.pop("domain", UNSET)

        id = d.pop("id", UNSET)

        level = d.pop("level", UNSET)

        name = d.pop("name", UNSET)

        _name_translations = d.pop("nameTranslations", UNSET)
        name_translations: Union[Unset, TermNameTranslations]
        if isinstance(_name_translations, Unset):
            name_translations = UNSET
        else:
            name_translations = TermNameTranslations.from_dict(_name_translations)

        occurrences = []
        _occurrences = d.pop("occurrences", UNSET)
        for occurrences_item_data in _occurrences or []:
            occurrences_item = TermOccurrence.from_dict(occurrences_item_data)

            occurrences.append(occurrences_item)

        ontology = d.pop("ontology", UNSET)

        parents = d.pop("parents", UNSET)

        privacy_budget_allocated = d.pop("privacyBudgetAllocated", UNSET)

        skipped_for_catalog = d.pop("skippedForCatalog", UNSET)

        total_children = d.pop("totalChildren", UNSET)

        total_descendant_occurrence = d.pop("totalDescendantOccurrence", UNSET)

        total_occurrence = d.pop("totalOccurrence", UNSET)

        uri = d.pop("uri", UNSET)

        version = d.pop("version", UNSET)

        term = cls(
            omop_concept_id=omop_concept_id,
            aggregated_occurrence=aggregated_occurrence,
            breadcrumb=breadcrumb,
            children=children,
            code=code,
            data_source_id=data_source_id,
            description=description,
            description_translations=description_translations,
            domain=domain,
            id=id,
            level=level,
            name=name,
            name_translations=name_translations,
            occurrences=occurrences,
            ontology=ontology,
            parents=parents,
            privacy_budget_allocated=privacy_budget_allocated,
            skipped_for_catalog=skipped_for_catalog,
            total_children=total_children,
            total_descendant_occurrence=total_descendant_occurrence,
            total_occurrence=total_occurrence,
            uri=uri,
            version=version,
        )

        term.additional_properties = d
        return term

    @property
    def additional_keys(self) -> List[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
